pages:
  stage: deploy
  script:
    # Creaci√≥n del directorio para GitLab Pages
    - mkdir public
    - cp -r doc/manual_tecnico/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master